"use client"
import { Inter } from "next/font/google";
import "./globals.css";
import TokenContext from "./components/context/TokenContext";
import { useState } from "react";


const inter = Inter({ subsets: ["latin"] });

/*export const metadata = {
  title: "Agas Bakery",
  description: "Generated by create next app",
};*/

export default function RootLayout({ children }) {
  const [token, setToken] = useState({})

  return (
    <html lang="en" className='bg-white text-gray-900 body-font text-lg  container  mx-auto'>
      <TokenContext.Provider value={({ token, setToken })}>
        <body className={inter.className}>{children}</body>
      </TokenContext.Provider>
    </html>
  );
}
