import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/MyNavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Agas Bakery Prototype",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-white text-gray-900 body-font text-lg  container  mx-auto'>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
